SurbeyParticipation Class + userResponse untested
CallMeLeon167/umfrageprojekt pull request #7
Opened 2024-06-14 16:03 UTC by CodeLars

2024-06-14 16:12 UTC, CodeLars commented
BEY

2024-06-15 10:59 UTC, Dhalion requested changes

2024-06-15 10:59 UTC, Dhalion commented on backend/app/DataStructure/SurveyRepository.php
> +        else if($populateParticipationUsers)
mit dem else if landest du aber in dem fall dass $result empty ist

2024-06-15 10:59 UTC, Dhalion commented on backend/app/DataStructure/userResponseRepository.php
> +                        return null;
würde hier ein [] (leeres array) returnen

2024-06-15 10:59 UTC, Dhalion commented on backend/app/DataStructure/userResponseRepository.php
> +                    }
würde hier $userResponses initialisieren, damit das auf jeden fall da ist. und mit dem db query null result als [] ist das auch immer vom type array

2024-07-01 10:17 UTC, closed without merging